---
title: "IndoorClimate"
author: "Claus Bo Hansen"
date: "October 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load libraries
library(tidyverse)
library(plotly)

```

The purpose of this page is to demonstrate plot_ly by showing an example of the relationship between indoor humidity and CO2 concentration and the temperature difference between indoor and outdoor for all Mondays during the last year.
Not surprisingly, the relative humidity drops in a heated house, when the outside temperature drops.


```{r}

# Load data
indoor <- read.csv("Stuen_11_10_2019.csv", skip = 2, sep = ";", stringsAsFactors = FALSE) %>%
  rename(IndoorTemp = Temperature,
         IndoorCO2 = CO2,
         IndoorHumidity = Humidity,
         Time = Timezone...Europe.Copenhagen) %>%
  mutate(Time = as.POSIXct(Time)) %>%
  select(Time, IndoorTemp, IndoorHumidity, IndoorCO2)
  
outdoor <- read.csv("Skuret_11_10_2019.csv", skip = 2, sep = ";") %>%
  rename(OutdoorTemp = Temperature,
         OutdoorHumidity = Humidity,
         Time = Timezone...Europe.Copenhagen) %>%
  mutate(Time = as.POSIXct(Time)) %>%
  select(Time, OutdoorTemp, OutdoorHumidity)


climatedata <- indoor %>%
  left_join(outdoor, by = "Time") %>%
  mutate(Temperaturedifference = IndoorTemp - OutdoorTemp) %>%
  filter(strftime(Time, '%A') == "Monday")

```

# 3D visualization

```{r}

plot_ly(climatedata, x = ~Temperaturedifference, y = ~IndoorCO2, z = ~IndoorHumidity) %>%
  add_markers(size = 1) %>%
  layout(dragmode = "orbit")

```

